name: patrol_presentation
description: "A presentation about Patrol - the Flutter E2E Testing Framework"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animated_to: ^0.3.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_deck: ^0.14.0
  flutter_hooks: ^0.20.5
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.4
  mesh: ^0.5.0
  qr_flutter: ^4.1.0
  rive: ^0.13.5
  url_launcher: ^6.2.4
  web_socket_channel: ^3.0.0

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/apple_news/
    - assets/rive/
  shaders:
    - assets/shaders/liquid_shader_lucas.frag
    - assets/shaders/liquid_shader_choyan.frag
  
  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/GraphikSemibold.otf
          weight: 600
        - asset: assets/fonts/GraphikMedium.otf
          weight: 500
        - asset: assets/fonts/GraphikRegular.otf
          weight: 400

flutter_gen:
  output: lib/generated
  line_length: 80
  integrations:
    flutter_svg: true
